#!/bin/bash

echo ''
echo ''
echo '-------------------------------------'
echo 'My Customized Python PROGRAM....NOT!!'
echo '-------------------------------------'
echo ''
echo 'Does NOTHING!!!'
echo ''
echo

